<!--
* Plantilla footer sacada desde https://mdbootstrap.com/
* Integración echa con hoja personalizada de css
-->
<footer class="footer mt-auto">
  <div class="text-center p-3 text-light" style="background-color: rgba(0, 0, 0, 0.7)">
    <p class="m-0">Prueba Técnica - Postulación Sistemas Expertos</p>
    <p class="m-0">2021 @ Nicolás Medina: 
    <a class="text-light" href="mailto:medinanicolas@protonmail.com">medinanicolas@protonmail.com</a></p>
  </div>
</footer>