
<!-- 
* Cambiar 'http://localhost' por el domain correspondiente 
-->

<!-- Boostrap 4 -->
<link rel='stylesheet' href='http://localhost/css/bootstrap.min.css'>
<script src="http://localhost/js/bootstrap.min.js"></script>
<!-- Custom CSS -->
<link rel='stylesheet' href='http://localhost/css/style.css'>
<!-- jQuery -->
<script src="http://localhost/js/jquery-3.5.1.min.js"></script>
<!-- Popper -->
<script src="http://localhost/js/popper.min.js"></script>
<!-- FontAwesome -->
<link rel='stylesheet' href='http://localhost/css/fontawesome/css/all.css'>
<!-- SweetAlert2 -->
<script src="http://localhost/js/sweetalert2.all.js"></script>

<!-- FavIcon -->
<link rel="icon" href="http://localhost/base/images/favicon.ico">