<!-- 
* Cambiar 'http://localhost' por el domain correspondiente'
-->
<nav class="navbar navbar-dark bg-dark navbar-expand-lg py-4 ">
    <a class="navbar-brand" href="http://localhost">GESTION DE BODEGAS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="http://localhost/admin/"><i class="fas fa-home"></i> INICIO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://localhost/admin/bodega/"><i class="fas fa-warehouse"></i> BODEGAS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://localhost/admin/productos"><i class="fas fa-box"></i> PRODUCTOS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://localhost/admin/entregas/"><i class="fas fa-truck-loading"></i> ENTREGAS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://localhost/admin/stock/"><i class="fas fa-boxes"></i> STOCK</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=""><i class="fas fa-user-friends"></i> USUARIOS</a>
            </li>
            <li class="nav">
                <a class="nav-link" href="http://localhost/login/logout.php"><i class="fas fa-sign-out-alt"></i> CERRAR SESION</a>
            </li>'
        </ul>
    </div>
</nav>